server:
  port: 9003

spring:
  application:
    name: msa-weather-data
  redis:
    password: root
    port: 6379
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

